-- ============================================================
-- 011_maid_documents_storage.sql
--
-- Creates the PRIVATE `maid-documents` Supabase Storage bucket used by
-- multimodal intake to store passport/ID images extracted from WhatsApp.
--
-- Passports are sensitive PII, so the bucket is NOT public. The CRM writes
-- with the service role (which bypasses RLS) and stores a long-lived SIGNED
-- URL in the maids app's `maid_documents.document_url`. No public-read policy.
--
-- File path convention:
--   maid-documents/{maid_id}/passport_<timestamp>.<ext>
--
-- Idempotent — safe to re-run.
-- ============================================================

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'maid-documents',
  'maid-documents',
  FALSE, -- PRIVATE: passport PII, served only via signed URLs
  10485760, -- 10 MB
  ARRAY['image/png', 'image/jpeg', 'image/webp', 'application/pdf']
)
ON CONFLICT (id) DO UPDATE
SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- No storage.objects policies are created: the only writer/reader is the
-- service role, which bypasses RLS. Adding public policies would defeat the
-- private-bucket intent. Signed URLs are generated by the CRM at insert time.
